type User {
  id: ID!
  email: String!
  name: String!
  bio: String
  gender: String
  birthDate: String
  photos: [String!]
  latitude: Float
  longitude: Float
  createdAt: String
  updatedAt: String
  matches1: [Match!]
  matches2: [Match!]
  messages: [Message!]
  posts: [Post!]
  swipesGiven: [Swipe!]
  swipesReceived: [Swipe!]
  tokens: Int
  superlikeTokens: Int
  dmTokens: Int
  hasLikedMe: Boolean
  hasSuperlikedMe: Boolean
}

type Query {
  users: [User!]
  getProfile(id: ID!): User!
}

type AuthPayload {
  user: User!
  accessToken: String!
}

type Mutation {
  loginWithGoogle(idToken: String!): AuthPayload!
  createUser(email: String!, password: String!, name: String!): AuthPayload!
  signUp(email: String!, password: String!, name: String!): AuthPayload!
  updateUser(id: ID!, email: String, password: String, name: String, bio: String, gender: String, birthDate: String, photos: [String!], latitude: Float, longitude: Float): User!
  logout: Boolean!
  deleteAccount: User!
  addTokens(amount: Int!): User!

  deleteUser(id: ID!): User!
  uploadPhoto(base64: String!): String!
  deletePhoto(url: String!): Boolean!
}